"""
Beautiful PPTX Builder.
Three slide layouts: title | content | section
"""
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def _rgb(hex_str):
    from pptx.dml.color import RGBColor
    try:
        h = str(hex_str).lstrip("#")
        if len(h) != 6:
            h = "1F4E79"
        return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))
    except Exception:
        from pptx.dml.color import RGBColor
        return RGBColor(0x1F, 0x4E, 0x79)


def _white():
    from pptx.dml.color import RGBColor
    return RGBColor(0xFF, 0xFF, 0xFF)


def _dark():
    from pptx.dml.color import RGBColor
    return RGBColor(0x22, 0x22, 0x22)


def _gray():
    from pptx.dml.color import RGBColor
    return RGBColor(0x77, 0x77, 0x77)


def _light_bg():
    from pptx.dml.color import RGBColor
    return RGBColor(0xF5, 0xF7, 0xFA)


def _rect(slide, left, top, width, height, color):
    s = slide.shapes.add_shape(1, int(left), int(top), int(width), int(height))
    s.fill.solid()
    s.fill.fore_color.rgb = color
    s.line.fill.background()
    return s


def _title_slide(prs, data, dna):
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    primary   = _rgb(dna["colors"]["primary"])
    secondary = _rgb(dna["colors"]["secondary"])
    palette   = dna["colors"].get("palette", [])
    accent    = _rgb(palette[2]) if len(palette) > 2 else RGBColor(0xED, 0x7D, 0x31)
    tfont     = dna["fonts"]["title"]
    bfont     = dna["fonts"]["body"]
    tsize     = float(dna["fonts"]["title_size"])

    w = prs.slide_width
    h = prs.slide_height
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    _rect(slide, 0, 0, w, h, primary)
    _rect(slide, 0, h - int(h * 0.22), w, int(h * 0.22), secondary)
    _rect(slide, 0, 0, Inches(0.12), h, accent)

    tb = slide.shapes.add_textbox(Inches(0.9), Inches(1.5), Inches(11.2), Inches(3.0))
    tf = tb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = data.get("title", "")
    p.font.name = tfont
    p.font.size = Pt(min(tsize * 1.3, 52))
    p.font.bold = True
    p.font.color.rgb = _white()

    subtitle = data.get("subtitle", "")
    if not subtitle:
        bullets = data.get("bullets", [])
        if bullets:
            subtitle = bullets[0]
    if subtitle:
        tb2 = slide.shapes.add_textbox(Inches(0.9), Inches(4.5), Inches(10.0), Inches(1.2))
        tf2 = tb2.text_frame
        tf2.word_wrap = True
        p2 = tf2.paragraphs[0]
        p2.text = subtitle
        p2.font.name = bfont
        p2.font.size = Pt(max(tsize * 0.55, 18))
        p2.font.color.rgb = RGBColor(0xBD, 0xD7, 0xFF)

    tb3 = slide.shapes.add_textbox(Inches(9.5), h - Inches(0.55), Inches(3.5), Inches(0.4))
    p3 = tb3.text_frame.paragraphs[0]
    p3.text = "Generated by BEACON"
    p3.font.size = Pt(9)
    p3.font.color.rgb = RGBColor(0xAA, 0xBB, 0xCC)
    p3.alignment = 2


def _content_slide(prs, data, dna, slide_num):
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    primary   = _rgb(dna["colors"]["primary"])
    secondary = _rgb(dna["colors"]["secondary"])
    palette   = dna["colors"].get("palette", [])
    accent    = _rgb(palette[2]) if len(palette) > 2 else RGBColor(0xED, 0x7D, 0x31)
    tfont     = dna["fonts"]["title"]
    bfont     = dna["fonts"]["body"]
    tsize     = float(dna["fonts"]["title_size"])
    bsize     = float(dna["fonts"]["body_size"])

    w = prs.slide_width
    h = prs.slide_height
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    _rect(slide, 0, 0, w, h, _light_bg())
    bar_h = int(h * 0.175)
    _rect(slide, 0, 0, w, bar_h, primary)
    _rect(slide, 0, bar_h, w, int(h * 0.008), accent)

    badge_w = Inches(0.55)
    badge_h = Inches(0.38)
    _rect(slide, w - badge_w - Inches(0.2), Inches(0.1), badge_w, badge_h, secondary)
    tbn = slide.shapes.add_textbox(w - badge_w - Inches(0.2), Inches(0.1), badge_w, badge_h)
    pn = tbn.text_frame.paragraphs[0]
    pn.text = str(slide_num)
    pn.font.name = tfont
    pn.font.size = Pt(11)
    pn.font.bold = True
    pn.font.color.rgb = _white()
    pn.alignment = 1

    tbt = slide.shapes.add_textbox(Inches(0.5), Inches(0.1), Inches(11.8), Inches(1.1))
    tbt.text_frame.word_wrap = True
    pt = tbt.text_frame.paragraphs[0]
    pt.text = data.get("title", "")
    pt.font.name = tfont
    pt.font.size = Pt(min(tsize * 0.72, 28))
    pt.font.bold = True
    pt.font.color.rgb = _white()

    _rect(slide, Inches(0.28), Inches(1.55), Inches(0.07), int(h * 0.72), secondary)
    _rect(slide, Inches(0.45), Inches(1.55), w - Inches(0.75), h - Inches(1.55) - Inches(0.3), _white())

    bullets = data.get("bullets", [])
    tbb = slide.shapes.add_textbox(Inches(0.75), Inches(1.75), Inches(12.1), Inches(5.3))
    tbb.text_frame.word_wrap = True

    bullet_colors = [
        primary, secondary, accent,
        _rgb(palette[3]) if len(palette) > 3 else RGBColor(0x70, 0xAD, 0x47),
        _rgb(palette[4]) if len(palette) > 4 else RGBColor(0xFF, 0xC0, 0x00),
    ]

    main_idx = 0
    for j, bullet in enumerate(bullets):
        para = tbb.text_frame.paragraphs[0] if j == 0 else tbb.text_frame.add_paragraph()
        is_sub = bullet.startswith("  ") or bullet.startswith("\t")
        text = bullet.strip()
        if is_sub:
            para.text = "      \u25e6  " + text
            para.font.name = bfont
            para.font.size = Pt(max(bsize * 0.82, 13))
            para.font.bold = False
            para.font.color.rgb = _gray()
        else:
            para.text = "  \u25cf  " + text
            para.font.name = bfont
            para.font.size = Pt(max(bsize, 15))
            para.font.bold = False
            para.font.color.rgb = _dark()
            main_idx += 1


def _section_slide(prs, data, dna):
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    secondary = _rgb(dna["colors"]["secondary"])
    palette   = dna["colors"].get("palette", [])
    accent    = _rgb(palette[2]) if len(palette) > 2 else RGBColor(0xED, 0x7D, 0x31)
    tfont     = dna["fonts"]["title"]
    bfont     = dna["fonts"]["body"]
    tsize     = float(dna["fonts"]["title_size"])

    w = prs.slide_width
    h = prs.slide_height
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    _rect(slide, 0, 0, w, h, secondary)
    # Darken secondary colour by 35 — parse from hex string
    _sec_hex = dna["colors"]["secondary"].lstrip("#")
    _sr = int(_sec_hex[0:2], 16)
    _sg = int(_sec_hex[2:4], 16)
    _sb = int(_sec_hex[4:6], 16)
    darker = RGBColor(max(0, _sr - 35), max(0, _sg - 35), max(0, _sb - 35))
    _rect(slide, 0, int(h * 0.62), w, int(h * 0.38), darker)
    _rect(slide, 0, 0, Inches(0.22), h, accent)

    sec_num = data.get("section_num", "")
    if sec_num:
        tbn = slide.shapes.add_textbox(Inches(0.55), Inches(0.7), Inches(3), Inches(1.5))
        pn = tbn.text_frame.paragraphs[0]
        pn.text = str(sec_num)
        pn.font.name = tfont
        pn.font.size = Pt(tsize * 1.8)
        pn.font.bold = True
        pn.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    tbt = slide.shapes.add_textbox(Inches(0.6), Inches(2.1), Inches(11.5), Inches(3.0))
    tbt.text_frame.word_wrap = True
    pt = tbt.text_frame.paragraphs[0]
    pt.text = data.get("title", "")
    pt.font.name = tfont
    pt.font.size = Pt(min(tsize * 1.15, 48))
    pt.font.bold = True
    pt.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    sub = data.get("subtitle", "")
    if sub:
        tbs = slide.shapes.add_textbox(Inches(0.6), Inches(5.1), Inches(10), Inches(0.9))
        ps = tbs.text_frame.paragraphs[0]
        ps.text = sub
        ps.font.name = bfont
        ps.font.size = Pt(16)
        ps.font.color.rgb = RGBColor(0xCC, 0xDD, 0xFF)


def build_beautiful_pptx(slides_content, style_dna, output_path):
    """
    Build a beautiful PPTX.
    slides_content : list of dicts (layout, title, bullets, subtitle, section_num)
    style_dna      : dict from extract_style_dna() or DEFAULT_DNA
    output_path    : str path for output .pptx
    """
    from pptx import Presentation
    from pptx.util import Inches

    prs = Presentation()
    prs.slide_width  = Inches(style_dna["slide_size"]["width_inches"])
    prs.slide_height = Inches(style_dna["slide_size"]["height_inches"])

    slide_num = 1
    for item in slides_content:
        layout = item.get("layout", "content").lower()
        if layout == "title":
            _title_slide(prs, item, style_dna)
        elif layout == "section":
            _section_slide(prs, item, style_dna)
        else:
            _content_slide(prs, item, style_dna, slide_num)
            slide_num += 1

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    prs.save(output_path)
    logger.info("Saved PPTX: %s (%d slides)", output_path, len(slides_content))
    return output_path
