#!/usr/bin/env python3
"""
core/vector_memory.py  -  Weaviate-backed semantic memory (async-native).

FIX (Step 7 of 14)
==================
Every synchronous Weaviate call is replaced with its native async
counterpart from weaviate-client v4 (WeaviateAsyncClient), and the
CPU-bound sentence-transformers encode() is moved off the event-loop
thread via asyncio.to_thread().

ROOT CAUSE
----------
The original code called ``weaviate.connect_to_local()`` which returns
the *synchronous* WeaviateClient.  All operations inside the
``_run_with_reconnect`` lambdas were blocking HTTP/gRPC calls executed
directly on the asyncio event-loop thread:

    self.client = weaviate.connect_to_local(...)          # blocks
    self.client.collections.get(name)                     # blocks
    collection.data.insert(properties, vector=v)          # blocks
    collection.query.near_vector(near_vector=v, ...)       # blocks
    collection.query.fetch_objects(limit=n)               # blocks
    collection.data.delete_by_id(uuid)                    # blocks
    collection.data.update(uuid, properties)              # blocks
    self._encoder.encode(text, ...)                       # CPU-bound, blocks

With a single-thread Uvicorn worker every one of these calls froze ALL
concurrent sessions until it returned.

FIX APPLIED
-----------
1.  ``import weaviate`` moved to module level (required for test mocking).
2.  ``weaviate.connect_to_local()``  =>  ``weaviate.use_async_with_local()``
    + ``await self._client.connect()``.
3.  Every collection operation is awaited (see inline comments).
4.  ``self._encoder.encode()`` runs in a thread-pool via
    ``asyncio.to_thread()``.
5.  ``_run_with_reconnect()`` scaffolding removed; each public method owns
    its own try/except + ``await self._mark_unavailable()`` on failure.
6.  ``def close()`` -> ``async def close()``.

No new dependencies: weaviate-client>=4.5.0 and sentence-transformers
are already in requirements.txt.
"""

import asyncio
import logging
import socket
from datetime import datetime
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse

import os as _os

# Module-level import so unittest.mock.patch('core.vector_memory.weaviate.use_async_with_local')
# resolves correctly at test time.
import weaviate

logger = logging.getLogger(__name__)

WEAVIATE_URL = f"http://localhost:{_os.getenv('WEAVIATE_PORT', '8090')}"
LOCAL_EMBEDDING_MODEL = "all-MiniLM-L6-v2"


class VectorMemory:
    """
    Weaviate-backed vector memory with client-side embeddings.

    Three collections:
      - ResearchMemory  : tool results, researched content
      - PersonalFacts   : user-provided personal details
      - AutoLearned     : facts extracted automatically from conversation

    Embeddings are generated by sentence-transformers running in a
    thread-pool worker (``asyncio.to_thread``) so CPU work never blocks
    the event loop.  All Weaviate I/O uses the v4 async client.
    """

    def __init__(
        self,
        openai_api_key: str = "",
        weaviate_url: str = WEAVIATE_URL,
        openai_base_url: str = "https://api.openai.com/v1",
        embedding_model: str = LOCAL_EMBEDDING_MODEL,
    ):
        self.weaviate_url = weaviate_url
        self.embedding_model = embedding_model

        self._client = None      # WeaviateAsyncClient (set in initialize)
        self._encoder = None     # SentenceTransformer (set in initialize)
        self._ready: bool = False

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def initialize(self) -> bool:
        """Connect to Weaviate, load local embedding model, ensure collections."""
        try:
            from sentence_transformers import SentenceTransformer

            # Load local embedding model (CPU-bound) in thread-pool.
            if self._encoder is None:
                logger.info(f"Loading local embedding model: {self.embedding_model}")
                self._encoder = await asyncio.to_thread(
                    SentenceTransformer,
                    self.embedding_model,
                    local_files_only=_os.getenv("TRANSFORMERS_OFFLINE", "0") == "1",
                )

            # Close stale client before reconnecting.
            if self._client is not None:
                try:
                    await self._client.close()
                except Exception:
                    pass

            parsed = urlparse(self.weaviate_url)
            host = parsed.hostname or "localhost"
            port = parsed.port or int(_os.getenv("WEAVIATE_PORT", "8090"))
            grpc_port = int(_os.getenv("WEAVIATE_GRPC_PORT", "50051"))

            # ✅ ASYNC: use_async_with_local returns WeaviateAsyncClient, no I/O yet.
            self._client = weaviate.use_async_with_local(
                host=host,
                port=port,
                grpc_port=grpc_port,
            )
            # ✅ ASYNC: opens HTTP + gRPC connections without blocking event loop.
            await self._client.connect()

            await self._ensure_collections()
            self._ready = True
            logger.info("VectorMemory initialized (Weaviate v4 async client)")
            return True

        except ImportError as exc:
            logger.error(
                f"Missing dependency: {exc}.  "
                "Run: pip install weaviate-client sentence-transformers"
            )
            self._ready = False
            return False
        except Exception as exc:
            logger.warning(f"VectorMemory not available: {exc}")
            self._ready = False
            self._client = None
            return False

    async def ensure_ready(self) -> bool:
        """Return True when ready; attempt reconnection when not."""
        if self._ready and self._client is not None:
            return True
        logger.info("VectorMemory is not ready, attempting reconnect")
        return await self.initialize()

    async def _mark_unavailable(self) -> None:
        """Tear down current client so the next call can attempt a fresh connect."""
        if self._client is not None:
            try:
                await self._client.close()
            except Exception:
                pass
        self._client = None
        self._ready = False

    def _is_grpc_reachable(self, timeout_seconds: float = 0.4) -> bool:
        """Fast TCP probe of the Weaviate gRPC port (sync, cheap)."""
        parsed = urlparse(self.weaviate_url)
        host = parsed.hostname or "localhost"
        grpc_port = int(_os.getenv("WEAVIATE_GRPC_PORT", "50051"))
        try:
            with socket.create_connection((host, grpc_port), timeout=timeout_seconds):
                return True
        except OSError:
            return False

    async def close(self) -> None:
        """Disconnect from Weaviate and release sentence-transformer workers.

        Changed from ``def close()`` (sync, blocked event loop on teardown)
        to ``async def close()`` so callers can properly await the disconnect.
        """
        # Shut down loky reusable executor to avoid semaphore leak warnings.
        try:
            from joblib.externals.loky import get_reusable_executor
            executor = get_reusable_executor()
            try:
                executor.shutdown(wait=True, kill_workers=True)
            except TypeError:
                executor.shutdown(wait=True)
        except Exception:
            pass

        try:
            from joblib.externals.loky.backend import resource_tracker as _rt
            tracker = getattr(_rt, "_resource_tracker", None)
            if tracker is not None:
                tracker._stop()
        except Exception:
            pass

        if self._client is not None:
            try:
                # ✅ ASYNC: was self.client.close() (sync)
                await self._client.close()
            except Exception:
                pass
            self._client = None
            self._ready = False

    # ------------------------------------------------------------------
    # Schema
    # ------------------------------------------------------------------

    async def _ensure_collections(self) -> None:
        """Create (or recreate) the three collections with no vectorizer."""
        import weaviate.classes.config as wc

        # ✅ ASYNC: was self.client.collections.list_all()  (sync)
        all_cols = await self._client.collections.list_all()
        existing = list(all_cols)  # keys are collection names

        for name in ["ResearchMemory", "PersonalFacts"]:
            if name in existing:
                try:
                    # ✅ ASYNC: was self.client.collections.get()  (sync)
                    col = self._client.collections.get(name)
                    # ✅ ASYNC: was col.config.get()  (sync)
                    cfg = await col.config.get()
                    vectorizer = str(getattr(cfg, "vectorizer_config", ""))
                    if "none" not in vectorizer.lower():
                        logger.info(f"Recreating {name} collection with none vectorizer")
                        # ✅ ASYNC: was self.client.collections.delete()  (sync)
                        await self._client.collections.delete(name)
                        existing.remove(name)
                except Exception:
                    await self._client.collections.delete(name)
                    if name in existing:
                        existing.remove(name)

        if "ResearchMemory" not in existing:
            # ✅ ASYNC: was self.client.collections.create()  (sync)
            await self._client.collections.create(
                name="ResearchMemory",
                vectorizer_config=wc.Configure.Vectorizer.none(),
                properties=[
                    wc.Property(name="tool_name",  data_type=wc.DataType.TEXT),
                    wc.Property(name="query",       data_type=wc.DataType.TEXT),
                    wc.Property(name="result",      data_type=wc.DataType.TEXT),
                    wc.Property(name="stored_at",   data_type=wc.DataType.TEXT),
                ],
            )
            logger.info("Created ResearchMemory collection")

        if "PersonalFacts" not in existing:
            await self._client.collections.create(
                name="PersonalFacts",
                vectorizer_config=wc.Configure.Vectorizer.none(),
                properties=[
                    wc.Property(name="topic",       data_type=wc.DataType.TEXT),
                    wc.Property(name="fact",        data_type=wc.DataType.TEXT),
                    wc.Property(name="stored_at",   data_type=wc.DataType.TEXT),
                ],
            )
            logger.info("Created PersonalFacts collection")

        if "AutoLearned" not in existing:
            await self._client.collections.create(
                name="AutoLearned",
                vectorizer_config=wc.Configure.Vectorizer.none(),
                properties=[
                    wc.Property(name="topic",       data_type=wc.DataType.TEXT),
                    wc.Property(name="fact",        data_type=wc.DataType.TEXT),
                    wc.Property(name="confidence",  data_type=wc.DataType.TEXT),
                    wc.Property(name="stored_at",   data_type=wc.DataType.TEXT),
                    wc.Property(name="updated_at",  data_type=wc.DataType.TEXT),
                ],
            )
            logger.info("Created AutoLearned collection")

    # ------------------------------------------------------------------
    # Embedding helper
    # ------------------------------------------------------------------

    async def _embed(
        self, text: str, label: str = "Encoding memory"
    ) -> Optional[List[float]]:
        """
        Generate an embedding vector.

        FIX: the original _embed() called self._encoder.encode() synchronously
        on the event-loop thread (CPU-bound).  Now we run it in a thread-pool
        worker via asyncio.to_thread() so the event loop stays responsive.
        """
        if self._encoder is None:
            return None
        try:
            # ✅ ASYNC: CPU-bound encode moved to thread pool
            vector = await asyncio.to_thread(
                self._encoder.encode,
                text[:2000],
                normalize_embeddings=True,
                show_progress_bar=False,
            )
            return vector.tolist()
        except Exception as exc:
            logger.error(f"Embedding failed: {exc}")
            return None

    # ------------------------------------------------------------------
    # Research memory
    # ------------------------------------------------------------------

    async def store_research(
        self, tool_name: str, query: str, result: str
    ) -> Optional[bool]:
        """Store a tool result in ResearchMemory."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            logger.info("store_research skipped: Weaviate gRPC unreachable")
            await self._mark_unavailable()
            return None
        try:
            truncated = result[:4000]
            vector = await self._embed(
                f"{tool_name}: {query}\n{truncated}", label="Storing research"
            )
            if vector is None:
                return False
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("ResearchMemory")
            # ✅ ASYNC: was collection.data.insert()  (sync)
            await collection.data.insert(
                properties={
                    "tool_name": tool_name,
                    "query":     query,
                    "result":    truncated,
                    "stored_at": datetime.now().isoformat(),
                },
                vector=vector,
            )
            logger.debug(f"Stored research: [{tool_name}] {query[:60]}")
            return True
        except Exception as exc:
            logger.error(f"store_research failed: {exc}")
            await self._mark_unavailable()
            return None

    async def search_research(
        self, query: str, limit: int = 5
    ) -> Optional[List[Dict[str, Any]]]:
        """Semantic search over ResearchMemory."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            vector = await self._embed(query)
            if vector is None:
                return []
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("ResearchMemory")
            # ✅ ASYNC: was collection.query.near_vector()  (sync)
            response = await collection.query.near_vector(
                near_vector=vector,
                limit=limit,
                return_properties=["tool_name", "query", "result", "stored_at"],
            )
            return [obj.properties for obj in response.objects]
        except Exception as exc:
            logger.error(f"search_research failed: {exc}")
            await self._mark_unavailable()
            return None

    # ------------------------------------------------------------------
    # Personal facts
    # ------------------------------------------------------------------

    async def store_personal_fact(
        self, topic: str, fact: str
    ) -> Optional[bool]:
        """Store a personal fact in PersonalFacts."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            vector = await self._embed(f"{topic}: {fact}")
            if vector is None:
                return False
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("PersonalFacts")
            # ✅ ASYNC: was collection.data.insert()  (sync)
            await collection.data.insert(
                properties={
                    "topic":     topic,
                    "fact":      fact,
                    "stored_at": datetime.now().isoformat(),
                },
                vector=vector,
            )
            logger.info(f"Stored personal fact [{topic}]: {fact[:80]}")
            return True
        except Exception as exc:
            logger.error(f"store_personal_fact failed: {exc}")
            await self._mark_unavailable()
            return None

    async def search_personal_facts(
        self, query: str, limit: int = 10
    ) -> Optional[List[Dict[str, Any]]]:
        """Semantic search over PersonalFacts."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            vector = await self._embed(query)
            if vector is None:
                return []
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("PersonalFacts")
            # ✅ ASYNC: was collection.query.near_vector()  (sync)
            response = await collection.query.near_vector(
                near_vector=vector,
                limit=limit,
                return_properties=["topic", "fact", "stored_at"],
            )
            return [obj.properties for obj in response.objects]
        except Exception as exc:
            logger.error(f"search_personal_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    async def get_all_personal_facts(
        self,
    ) -> Optional[List[Dict[str, Any]]]:
        """Return all stored personal facts."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("PersonalFacts")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(
                limit=200,
                return_properties=["topic", "fact", "stored_at"],
            )
            return [obj.properties for obj in response.objects]
        except Exception as exc:
            logger.error(f"get_all_personal_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    async def delete_personal_facts(self, keyword: str) -> Optional[int]:
        """Delete personal facts whose topic or fact text contains the keyword."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("PersonalFacts")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(
                limit=500, return_properties=["topic", "fact"]
            )
            lower_kw = keyword.lower()
            to_delete = [
                obj.uuid for obj in response.objects
                if lower_kw in (obj.properties.get("topic") or "").lower()
                or lower_kw in (obj.properties.get("fact") or "").lower()
            ]
            for uid in to_delete:
                # ✅ ASYNC: was collection.data.delete_by_id()  (sync)
                await collection.data.delete_by_id(uid)
            logger.info(
                f"Deleted {len(to_delete)} personal fact(s) matching '{keyword}'"
            )
            return len(to_delete)
        except Exception as exc:
            logger.error(f"delete_personal_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    async def delete_research(self, keyword: str) -> Optional[int]:
        """Delete research entries whose query or result contains the keyword."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("ResearchMemory")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(
                limit=500,
                return_properties=["tool_name", "query", "result"],
            )
            lower_kw = keyword.lower()
            to_delete = [
                obj.uuid for obj in response.objects
                if lower_kw in (obj.properties.get("query") or "").lower()
                or lower_kw in (obj.properties.get("result") or "").lower()
            ]
            for uid in to_delete:
                # ✅ ASYNC: was collection.data.delete_by_id()  (sync)
                await collection.data.delete_by_id(uid)
            logger.info(
                f"Deleted {len(to_delete)} research entry/entries matching '{keyword}'"
            )
            return len(to_delete)
        except Exception as exc:
            logger.error(f"delete_research failed: {exc}")
            await self._mark_unavailable()
            return None

    async def clear_all_research(self) -> Optional[int]:
        """Delete all research memory entries."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("ResearchMemory")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(limit=5000)
            count = len(response.objects)
            for obj in response.objects:
                # ✅ ASYNC: was collection.data.delete_by_id()  (sync)
                await collection.data.delete_by_id(obj.uuid)
            logger.info(f"Cleared all {count} research memory entries")
            return count
        except Exception as exc:
            logger.error(f"clear_all_research failed: {exc}")
            await self._mark_unavailable()
            return None

    # ------------------------------------------------------------------
    # Auto-learned memory
    # ------------------------------------------------------------------

    async def store_auto_fact(
        self, topic: str, fact: str, confidence: str = "medium"
    ) -> Optional[bool]:
        """Store an auto-extracted fact; updates existing entry if topic matches."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("AutoLearned")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            existing = await collection.query.fetch_objects(
                limit=200, return_properties=["topic", "fact"]
            )
            lower_topic = topic.lower()
            for obj in existing.objects:
                if (obj.properties.get("topic") or "").lower() == lower_topic:
                    # ✅ ASYNC: was collection.data.update()  (sync)
                    await collection.data.update(
                        uuid=obj.uuid,
                        properties={
                            "fact": fact,
                            "confidence": confidence,
                            "updated_at": datetime.now().isoformat(),
                        },
                    )
                    logger.info(f"Updated auto-fact [{topic}]")
                    return True
            vector = await self._embed(f"{topic}: {fact}", label="Auto-learning")
            if vector is None:
                return False
            # ✅ ASYNC: was collection.data.insert()  (sync)
            await collection.data.insert(
                properties={
                    "topic":      topic,
                    "fact":       fact,
                    "confidence": confidence,
                    "stored_at":  datetime.now().isoformat(),
                    "updated_at": datetime.now().isoformat(),
                },
                vector=vector,
            )
            logger.info(f"Stored auto-fact [{topic}]: {fact[:80]}")
            return True
        except Exception as exc:
            logger.error(f"store_auto_fact failed: {exc}")
            await self._mark_unavailable()
            return None

    async def get_all_auto_facts(
        self,
    ) -> Optional[List[Dict[str, Any]]]:
        """Return all auto-learned facts."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("AutoLearned")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(
                limit=200,
                return_properties=[
                    "topic", "fact", "confidence", "stored_at", "updated_at"
                ],
            )
            return [obj.properties for obj in response.objects]
        except Exception as exc:
            logger.error(f"get_all_auto_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    async def search_auto_facts(
        self, query: str, limit: int = 10
    ) -> Optional[List[Dict[str, Any]]]:
        """Semantic search over AutoLearned collection."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            vector = await self._embed(query)
            if vector is None:
                return []
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("AutoLearned")
            # ✅ ASYNC: was collection.query.near_vector()  (sync)
            response = await collection.query.near_vector(
                near_vector=vector,
                limit=limit,
                return_properties=[
                    "topic", "fact", "confidence", "stored_at"
                ],
            )
            return [obj.properties for obj in response.objects]
        except Exception as exc:
            logger.error(f"search_auto_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    async def delete_auto_facts(self, keyword: str) -> Optional[int]:
        """Delete auto-learned facts matching keyword."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("AutoLearned")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(
                limit=500, return_properties=["topic", "fact"]
            )
            lower_kw = keyword.lower()
            to_delete = [
                obj.uuid for obj in response.objects
                if lower_kw in (obj.properties.get("topic") or "").lower()
                or lower_kw in (obj.properties.get("fact") or "").lower()
            ]
            for uid in to_delete:
                # ✅ ASYNC: was collection.data.delete_by_id()  (sync)
                await collection.data.delete_by_id(uid)
            return len(to_delete)
        except Exception as exc:
            logger.error(f"delete_auto_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    async def clear_auto_facts(self) -> Optional[int]:
        """Clear all auto-learned facts."""
        if not await self.ensure_ready():
            return None
        if not self._is_grpc_reachable():
            await self._mark_unavailable()
            return None
        try:
            # ✅ ASYNC: was self.client.collections.get()  (sync)
            collection = self._client.collections.get("AutoLearned")
            # ✅ ASYNC: was collection.query.fetch_objects()  (sync)
            response = await collection.query.fetch_objects(limit=5000)
            count = len(response.objects)
            for obj in response.objects:
                # ✅ ASYNC: was collection.data.delete_by_id()  (sync)
                await collection.data.delete_by_id(obj.uuid)
            logger.info(f"Cleared {count} auto-learned facts")
            return count
        except Exception as exc:
            logger.error(f"clear_auto_facts failed: {exc}")
            await self._mark_unavailable()
            return None

    # ------------------------------------------------------------------
    # Context builder
    # ------------------------------------------------------------------

    async def build_context_prompt(self, user_query: str) -> str:
        """Build a memory context string to inject into the system prompt."""
        sections = []

        facts = await self.search_personal_facts(user_query, limit=10) or []
        if facts:
            lines = [f"  - [{f['topic']}] {f['fact']}" for f in facts]
            sections.append(
                "\U0001f4cb What I know about you:\n" + "\n".join(lines)
            )

        auto_facts = await self.search_auto_facts(user_query, limit=8) or []
        if auto_facts:
            lines = [f"  - [{f['topic']}] {f['fact']}" for f in auto_facts]
            sections.append(
                "\U0001f9e0 What I've learned about you:\n" + "\n".join(lines)
            )

        research = await self.search_research(user_query, limit=3) or []
        if research:
            lines = []
            for r in research:
                snippet = r["result"][:300].replace("\n", " ")
                lines.append(
                    f"  - [{r['tool_name']}] {r['query'][:60]}\n    {snippet}..."
                )
            sections.append(
                "\U0001f50d Relevant past research:\n" + "\n".join(lines)
            )

        if not sections:
            return ""

        return (
            "=== MEMORY CONTEXT ===\n"
            + "\n\n".join(sections)
            + "\n=== END MEMORY CONTEXT ===\n\n"
        )
